openapi: '3.0.0'
info:
  title: Places App API
  version: 1.0.0
  description: Places App API Documentation
servers:
  - url: http://localhost:3001 

tags:
  - name: Places
    description: The places endpoint
  - name: Users
    description: The users endpoint

paths:
  /api/places:
    get:
      summary: Returns a list of all Places
      tags: [Places]
      responses:
        '200':
          description: Successfully returned a list of places
          content:
            application/json:
              schema:
                description: List of a places
                type: array
                items:
                  $ref: '#/components/schemas/Place'
  /api/places/{id}:
    get:
      summary: Returns a Place by ID
      tags: [Places]
      parameters:
      - name: id
        in: path
        description: ID of place to return
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successfully returned a place
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
        '400':
          description: Invalid Place ID
        '404':
          description: Place ID not found
  /api/users:
    get:
      summary: Returns a list of all Users
      tags: [Users]
      responses:
        '200':
          description: Successfully returned a list of users
          content:
            application/json:
              schema:
                description: List of a users
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /api/users/{id}:
    get:
      summary: Returns a User by ID
      tags: [Users]
      parameters:
      - name: id
        in: path
        description: ID of user to return
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successfully returned a user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid User ID
        '404':
          description: User not found
 
components:
  schemas:
    Place:
      type: object
      properties:
        ID:
          type: integer
          description: The ID of the Place
        Name:
          type: string
          description: The name of the Place
        UserID:
          type: integer
          description: The ID of the user who created the place
        UserName:
          type: string
          description: The name of the user who created the place
        Latitude: 
          type: number
          description: The latitude of the place
        Longitude:
          type: number
          description: The longitud of the place
      example:
        ID: 1
        Name: Some place
        UserId: 1
        UserName: Radu
        Latitude: 62.6120
        Longitude: 29.6910
    User:
      type: object
      properties:
        ID:
          type: integer
          description: User ID
        Name:
          type: string
          description: User name
        Password:
          type: string
          description: User password
      example:
        ID: 105
        Name: Pia
        Password: passw0rd


